server:
  port: ${SERVER_PORT:9094}
spring:
  application:
    name: gateway-svc
zuul:
  ignoredServices: '*'
  routes:
    customer:
      path: /customer/**
      serviceId: customer-svc
      sensitive-headers:
    message-svc:
      path: /message/**
      serviceId: message-svc
      sensitive-headers:
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SVC_DISCOVERY:http://user:password@${SERVER_URL:localhost}:9091/eureka/}